### ISSUE TITLE
Disabling the CRTC cursor disables screen updates

### ISSUE THREAD

**Issue by Screwtapello** [sethm/symon#5] opened 2023-01-06 06:32 UTC
First of all, thanks for making Symon! For someone just getting into 6502 programming, it's great to have a 6502 emulator with a simple memory map, simple I/O devices, that just loads a ROM my assembler toolchain produces.

I have noticed one puzzling behaviour, however, with the CRTC output.

Let's say I have the following program:

```asm
; Draw 'A' at the top-left position
lda #$41
sta $7000
```

I assemble it, I run `java -jar symon-1.3.2.jar -rom symon-demo.rom`, I enable the Video Window from the View menu, then I hit Run. In the top left corner of the Video window, underneath the blinking cursor, I get a capital `A` as expected. But that blinking cursor is distracting, let's try turning it off:

```asm
 ; select CRTC register 10, Cursor Start/Blink
lda #$0A
sta $9000
; Leave the start scanline at 0, set the blink mode to 01, hide cursor
lda #$10
sta $9000

; Draw 'A' at the top-left position
lda #$41
sta $7000
```

Now when I assemble and run the ROM, the Video window just stops updating: the cursor stops blinking, the top left position never changes to `A`. If I close the Video window and then re-open it, it correctly shows the new state.

Possibly related: if I click "Hard Reset" in the UI, the cursor does not resume blinking, even if I close and re-open the window.

**Comment by sethm** [comment] 2023-01-07 03:18
Thanks for finding this! I haven't dug into this code in years, so it might take me some time to re-familiarize myself with it and figure out what's going on.

**Comment by sethm** [comment] 2023-01-09 17:50
Can I assume that in the example program you've provided, you meant `$9001` for turning off the cursor? i.e., is it this?:

```asm
lda #$0A
sta $9000
lda #$10
sta $9001
lda #$41
sta $7000
```

**Comment by sethm** [comment] 2023-01-09 18:16
So far I'm not able to reproduce the behavior you're seeing. Here's a test program I assembled with ca65 and linked with ld65 and the memory configuration below:

```asm
        .setcpu "6502"
        .segment "OS"
start:
        ;; Write FOO
        lda #$46 ; F
        sta $7000
        lda #$4F ; O
        sta $7001
        sta $7002
        ;; Select the cursor start register
        lda #$0A
        sta $9000
        ;; Disable cursor 
        ;; by writing #$20 into the cursor start register
        lda #$10
        sta $9001
        ;; Now write BAR
        lda #$42 ; B
        sta $7000
        lda #$41 ; A
        sta $7001
        lda #$52 ; R
        sta $7002
        ;; Finally, re-enable the cursor
        ;; by writing #$40 into the cursor start register
        lda #$40
        sta $9001
        ;; End in an infinite loop
loop:   jmp loop

        .segment "VECTORS"
        .word start
        .word start
        .word start

.end
```

Linker Config:

```
MEMORY
{
    ZP: start=$0, size=$100, type=rw, define=yes;
   RAM: start=$200, size=$3e00, type=rw, define=yes;
   ROM: start=$c000, size=$4000, type=ro, define=yes, fill=yes, file=%O;
}

SEGMENTS
{
  ZEROPAGE: load=ZP, type=zp;
  DATA:     load=RAM, type=rw, define=yes;
  OS:       load=ROM, type=ro;
  RODATA:   load=ROM, type=ro;
  VECTORS:  load=ROM, type=ro, offset=$ffa;
}
```

Then assemble and link into `test.bin` ROM image:

```
ca65 test.asm
ld65 test.o -o test.bin -C test.cfg
```

If I load this ROM, set the PC to $C000 and let it run, it seems to behave correctly for me. I wonder if there's a platform difference? Can you tell me what platform you're running on?

**Comment by Screwtapello** [comment] 2023-01-10 07:39
> Can I assume that in the example program you've provided, you meant $9001 for turning off the cursor?

Sorry, yes. In my original source it was `CRTC_REG_VAL` and I typo'd while removing fancy assembler tricks. Your corrected code reproduces the problem in my environment:

```asm
lda #$0A
sta $9000
lda #$10
sta $9001
lda #$41
sta $7000
```

If I add an infinite loop at the end:

```asm
lda #$0A
sta $9000
lda #$10
sta $9001
lda #$41
sta $7000
loop:
jmp loop
```

...then the screen *does* update: the "A" appears at the top-left, and the cursor is invisible. On the other hand, if I instead turn the cursor back on:

```asm
lda #$0A
sta $9000
lda #$10
sta $9001
lda #$41
sta $7000
lda #$40
sta $9001
```

...then it again works as expected: the "A" appears at the top-left, and the cursor resumes blinking. It seems to just be the combination of:

- turn off the cursor
- write to the screen
- `BRK` to terminate the program

...that causes the screen to stop updating. 

I've attached assembled ROMs of the above three programs in a ZIP, in case that helps:
[testcases.zip](https://github.com/sethm/symon/files/10380129/testcases.zip)

I can confirm your test program does work for me (not surprising, since it includes both the infinite loop and turns the cursor back on).

> Can you tell me what platform you're running on?

I'm using Debian Testing, and using the X11 windowing system with a compositor enabled.

```
$ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Debian-2)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Debian-2, mixed mode, sharing)
```

**Comment by Screwtapello** [comment] 2023-01-10 08:25
I just tested using the GNOME desktop and Wayland windowing system (which is the system default, and therefore presumably more reliable) and got the same result.

**Comment by sethm** [comment] 2023-01-11 21:35
I think I've fixed it!

There was definitely a bug. The video window would only repaint if the cursor was actively blinking, otherwise it would remain in its last state until forced to repaint by (for example) closing and opening the window.

Please give the current head of the master branch a try and see if it solves the problem.

**Comment by sethm** [comment] 2023-01-11 21:35
I forgot to add, if you can't build it yourself let me know and I will upload a new release.

**Comment by Screwtapello** [comment] 2023-01-12 06:59
I can confirm the current head of the master branch (0bad9912ce1988c0b6af3f22a9adf3f175fd6879) works as expected. However, I had to apply the following patch to get it to build:

```patch
diff --git a/src/test/java/com/loomcom/symon/CrtcTest.java b/src/test/java/com/loomcom/symon/CrtcTest.java
index 06e0740..a92c339 100644
--- a/src/test/java/com/loomcom/symon/CrtcTest.java
+++ b/src/test/java/com/loomcom/symon/CrtcTest.java
@@ -8,7 +8,7 @@ import org.junit.Before;
 import org.junit.Test;
 import org.junit.runner.RunWith;
 import org.mockito.Mock;
-import org.mockito.runners.MockitoJUnitRunner;
+import org.mockito.junit.MockitoJUnitRunner;
 
 import static org.junit.Assert.assertEquals;
 import static org.junit.Assert.assertFalse;
```

...as suggested in https://stackoverflow.com/a/70595384

Thanks for looking into it!

**Comment by sethm** [comment] 2023-01-13 00:46
Thanks for letting me know! I'll make the Mockito change as well.

**Comment by sethm** [comment] 2023-01-13 05:00
Closing this issue because I believe it's fixed now, including the update to the correct Mockito package.

**Closed as completed by sethm** 2023-01-13 05:00 UTC

**Comment by Screwtapello** [comment] 2023-01-13 05:13
I can confirm the latest commit (e210a4063985ebec51bac8bdbb62d66973409a1b) fixes the issue and builds cleanly for me.
